[project]
name = "nuc-ai-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jean Rangel", email = "jcrs80@icloud.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "qdrant-client>=1.19.1",
    "sqlmodel>=0.0.42",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
nuc-ai-core = "nuc_ai_core:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
